### PR TITLE
Update webpack dependencies and everything around babel

### PR DESCRIPTION
**Pull request by PierreRambaud**
It prevents security issues with jquery 2, and update dependencies:
```
autoprefixer                  ^6.7.7  →   ^9.0.1 
 babel-loader                  ^5.3.2  →   ^7.1.5 
 bootstrap-touchspin           ^3.1.1  →   ^4.2.5 
 css-loader                   ^0.27.3  →   ^1.0.0 
 extract-text-webpack-plugin   ^2.1.0  →   ^3.0.2 
 file-loader                  ^0.10.1  →  ^1.1.11 
 flexibility                   ^1.0.5  →   ^2.0.1 
 jquery                        ^2.1.4  →   ^3.3.1 
 material-design-icons         ^2.1.3  →   ^3.0.1 
 postcss-flexibility           ^1.0.2  →   ^2.0.0 
 postcss-loader                ^1.3.3  →   ^2.1.6 
 sass-loader                   ^6.0.3  →   ^7.0.3 
 style-loader                 ^0.14.0  →  ^0.21.0 
 webpack                       ^2.2.1  →  ^4.16.1 
 webpack-sources               ^0.1.0  →   ^1.1.0
```

Maybe we can move your module under PrestaShop repository? (`ps_searchbarjqauto`)

### CODE REVIEW

**Comment by prestarocket** [comment]
For ps_searchbarjqauto, yes but you have to create the repo first. thx

**Comment by GuillaumeKadolis** [comment]
From babel 

If you are using Babel version 7 you will need to run npm install @babel/preset-env and have "presets": ["@babel/preset-env"] in your configuration

use "babel-preset-env": "^1.7.0", instead babel-preset-es2015

**Comment by prestarocket** [comment]
@PierreRambaud what do you think about @GuillaumeKadolis 's comment ?

**Comment by PierreRambaud** [comment]
He's true, but it's need more change than I did, to make it works with babel-preset-env`. Let's have a check on this PR, make sure everything's ok (I navigate, buy items and ok for me, but not sure I tried every cases =) ).
And after could be cool to optimise the webpack configuration file and add `babel-preset-env` :)

**Comment by GuillaumeKadolis** [comment]
i'm not sure it's the best solution to use webpack 4 + extract-text-webpack-plugin beta
i think it's not a good idea to use betas version in prod

i'll go on something like this instead which use webpack 3 and extract-text-webpack-plugin 3 (i can make a clean pull-request if you prefer but discussion is here. I may be forgotten to clean 1 or 2 (peer/dev)Dependencies i made this quick, it's just an idea, not clean tested version)
ps: 
[webpack_package_babel.zip](https://github.com/PrestaShop/classic-rocket/files/2222502/webpack_package_babel.zip)

**Comment by PierreRambaud** [comment]
Pr too old, I close it :)

**Pull request closed without merging**
