### PR TITLE
improved menu ergonomics

### PR DESCRIPTION
**Pull request by GuillaumeKadolis**
+ Increase menu links click zones, to allow user to click around links (top and bottom) not only right on it
+ align logo and menu
+ reduce first sub-menu width (he exceeded the layout with on hover)

### CODE REVIEW

**Comment by prestarocket** [comment]
thx, i ll test it before merge

**Comment by backamblock** [comment]
please merge it :)

**Comment by prestarocket** [comment]
@GuillaumeKadolis could you plz make the PR on branch 1.7.4.x ? thx

**Comment by GuillaumeKadolis** [comment]
@prestarocket  done

**Pull request merged**
